# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS
# ===============================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=test
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/test

# ===============================
# HIBERNATE ORM (JPA + PANACHE)
# ===============================

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# ===============================
# SWAGGER / OPENAPI
# ===============================

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

# ===============================
# CONFIGURAÇÕES GERAIS
# ===============================

quarkus.http.port=8080